AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Prefix:
    Type: String
    Description: Challenge Team Prefix

Resources:
  InputQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sqs-simple.yaml
      Parameters:
        Name: !Join [ '-', [ !Ref Prefix, 'input-queue' ] ]
  OutputQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sqs-simple-output.yaml
      Parameters:
        Name: !Join [ '-', [ !Ref Prefix, 'output-queue' ] ]
  simpleLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda-simple.yaml
      Parameters:
        Name: !Join [ '-', [ !Ref Prefix, 'venus-lambda' ] ]

