---
AWSTemplateFormatVersion: '2010-09-09'
Description: An SQS object to demonstrate CFT Deployments

Resources:
  InputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NameInputQueue

  OutputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NameOutputQueue

