---
AWSTemplateFormatVersion: '2010-09-09'
Description: An SQS object to demonstrate CFT Deployments

Parameters:
  Name:
    Type: String
    Default: "output-queue"

Resources:
  InputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Ref: Name


